#!/bin/bash
function usage()
{
    echo "Automatically runs Snakemake assembly pipeline"
    echo ""
    echo "Usage:"
    echo "./assemble.sh [MANDATORY] n_cores assembly_name supernova_max_reads assembly_type BUSCO_dataset [SETUP] /path/to/mkfastq_DIR /path/to/longranger/basic/file.fq.gz [OTHER_SMK_ARGS]"
    echo ""
    echo "MANDATORY Variables:"
    echo "n_cores = Number of cores to use. Minimum 32"
    echo "assembly_name = Name of assembly. Matches the directory data/NAME"
    echo "supernova_max_reads = Number of reads to use in Supernova. If you want to use all, set as \"all\""
    echo "assembly_type = \"chromium\" or \"nano\" - use nano if supplying nanopore data at data/[assembly_name]/nanopore"
    echo "BUSCO_dataset = absolute path to BUSCO dataset for benchmarking"
    echo ""
    echo "If you have not set up the working directory for the pipeline then you need to set the SETUP variables. If you have then use a single period (\".\") for each of these positional arguments"
    echo ""
    echo "SETUP variables:"
    echo "/path/to/mkfastq_DIR = absolute path to the directory containing the longranger mkfastq fastq.gz files. The only *.gz files from this should be the two fastq files generated by longranger mkfastq"
    echo "/path/to/longranger/basic/file.fq.gz = absolute path to the longranger basic fastq file"
    echo ""
    echo "OTHER_SMK_ARGS:"
    echo "Pass additional snakemake arguments here ie. -n for dryrun"
}

if [ "$1" == "" ]
then
    usage
    exit
fi

if [ ! -d "data/$2" ]
then
    mkdir data/$2
    mkdir data/$2/basic
    mkdir data/$2/mkfastq
    ln -s $6/*.gz data/$2/mkfastq/
    ln -s $7 data/$2/basic/basic.fq.gz
    echo "Created data/$2"
    echo "Created data/$2/basic/"
    echo "Created data/$2/mkfastq"
    echo "linked files ending in .gz in $6 to data/$2/mkfastq/"
    echo "Linked $7 to data/$2/basic/basic.fq.gz"
    echo "Generated data directory"
fi

if [ ! -d data/$2/mkfastq/ ]
then
    echo "Error: No mkfastq files found. Exiting"
    usage
    exit
fi

if [ ! -f data/$2/basic/basic.fq.gz ]
then
    echo "Error: No basic files found. Exiting"
    usage
    exit
fi
echo "$0 ${@:1}"
/home/lculibrk/miniconda3/bin/snakemake -s /projects/lculibrk_prj/CGEN150/pipeline/Snakefile -j$1 --config prefix=$2 reads=$3 type=$4 dataset=$5 -p ${@:8}
